#cloud-config
ssh_authorized_keys:
%{ for _ in ssh_authorized_keys }
  - ${_}
%{ endfor }

users:
  - default
  - name: etcd
    homedir: /var/lib/rancher/rke2/server/db
    system: true
  - name: rke2
    homedir: /var/lib/rancher/rke2
    system: true
